--
-- CREATE STRUCTURE of dbmig Schema in dbmig database
--
-- *************************************************
-- 1) Create schema
-- *************************************************

-- *************************************************
-- 2) Create integrity trigger functions on insert/update :
-- fk_id_batch_insert
-- fk_id_environmental_characteristic_insert
-- fk_id_observations_insert
-- integrity_observation_places_verify
-- integrity_observations_verify
-- observation_id_place_insert
-- observation_id_place_update
-- observations_id_insert
-- observations_id_update
-- *************************************************

-- *************************************************
-- 3) Create tables and Views
-- !!!!!! BEWARE : When creating Views, you need dbmig_nomenclature schema to be created !!!!!!
-- *************************************************

-- *************************************************
-- 4) Create autogenerated IDs with uuid_generate_v4 function
-- *************************************************

-- *************************************************
-- 5) Creating Indexes with B-Trees
-- *************************************************

-- *************************************************
-- 6) Linking insert/update with previsously created trigger functions
-- *************************************************

-- *************************************************
-- 7) Foreign keys constraints
-- !!!!!! BEWARE : at this stage, you need dbmig_nomenclature schema to be created !!!!!!
-- *************************************************

-- *************************************************
-- 8) grant functions and tables to dbmig_read
-- *************************************************

--
-- TOC entry 40 (class 2615 OID 2557612)
-- Name: dbmig; Type: SCHEMA; Schema: -; Owner: postgres
--

-- *************************************************
-- 1) Create schema
-- *************************************************

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA dbmig;
ALTER SCHEMA dbmig OWNER TO diaspara_admin;
GRANT USAGE ON SCHEMA dbmig TO diaspara_read;



-- *************************************************
-- 2) Create integrity trigger functions on insert/update :
-- fk_id_batch_insert
-- fk_id_environmental_characteristic_insert
-- fk_id_observations_insert
-- integrity_observation_places_verify
-- integrity_observations_verify
-- observation_id_place_insert
-- observation_id_place_update
-- observations_id_insert
-- observations_id_update
-- *************************************************

--
-- TOC entry 2632 (class 1255 OID 2557658)
-- Name: fk_id_batch_insert(); Type: FUNCTION; Schema: dbmig; Owner: postgres
--

CREATE FUNCTION dbmig.fk_id_batch_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  PERFORM ob_id FROM "dbmig".observations WHERE ob_id = NEW.ba_ob_id;
  IF FOUND THEN
	RETURN NEW;
  ELSE
	RAISE EXCEPTION '6- Invalid ba_ob_id (%)', NEW.ba_ob_id;
  END IF;
END
$$;


ALTER FUNCTION dbmig.fk_id_batch_insert() OWNER TO diaspara_admin;

--
-- TOC entry 2633 (class 1255 OID 2557659)
-- Name: fk_id_environmental_characteristic_insert(); Type: FUNCTION; Schema: dbmig; Owner: postgres
--
/*
CREATE FUNCTION dbmig.fk_id_environmental_characteristic_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  PERFORM op_id FROM "dbmig".observation_places WHERE op_id = NEW.ec_op_id;
  IF FOUND THEN
	RETURN NEW;
  ELSE
	RAISE EXCEPTION '5- Invalid ec_op_id (%)', NEW.ec_op_id;
  END IF;
END
$$;


ALTER FUNCTION dbmig.fk_id_environmental_characteristic_insert() OWNER TO diaspara_admin;
*/
--
-- TOC entry 2634 (class 1255 OID 2557660)
-- Name: fk_id_observations_insert(); Type: FUNCTION; Schema: dbmig; Owner: postgres
--

CREATE FUNCTION dbmig.fk_id_observations_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  PERFORM op_id FROM "dbmig".observation_places WHERE op_id = NEW.ob_op_id;
  IF FOUND THEN
	RETURN NEW;
  ELSE
	RAISE EXCEPTION '5- Invalid ob_op_id (%)', NEW.ob_op_id;
  END IF;
END
$$;


ALTER FUNCTION dbmig.fk_id_observations_insert() OWNER TO diaspara_admin;

--
-- TOC entry 2635 (class 1255 OID 2557661)
-- Name: integrity_observation_places_verify(); Type: FUNCTION; Schema: dbmig; Owner: postgres
--
drop function if exists dbmig.integrity_observation_places_verify() cascade;
CREATE FUNCTION dbmig.integrity_observation_places_verify() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  PERFORM ob_op_id FROM "dbmig".observations WHERE ob_op_id = OLD.op_id;
  IF FOUND THEN
	RAISE EXCEPTION '6- You try to delete an observation places record while there is some records in observations refering to it. op_id: (%)', OLD.op_id;
/*
  ELSE
	PERFORM ec_op_id FROM "dbmig".environmental_characteristic WHERE ec_op_id = OLD.op_id;
	IF FOUND THEN
		RAISE EXCEPTION '6- You try to delete an observation places record while there is some records in environmental_characteristic refering to it. op_id: (%)', OLD.op_id;
		ELSE
			RETURN OLD;
		END IF;
*/
  END IF;
END
$$;


ALTER FUNCTION dbmig.integrity_observation_places_verify() OWNER TO diaspara_admin;

--
-- TOC entry 2636 (class 1255 OID 2557662)
-- Name: integrity_observations_verify(); Type: FUNCTION; Schema: dbmig; Owner: postgres
--

CREATE FUNCTION dbmig.integrity_observations_verify() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  PERFORM ba_ob_id FROM "dbmig".batch WHERE ba_ob_id = OLD.ob_id;
  IF FOUND THEN
	RAISE EXCEPTION '6- You try to delete an observation record while there is some records in batch refering to it. ob_id: (%)', OLD.ob_id;
  ELSE
	RETURN OLD;
  END IF;
END
$$;


ALTER FUNCTION dbmig.integrity_observations_verify() OWNER TO diaspara_admin;

--
-- TOC entry 2637 (class 1255 OID 2557663)
-- Name: observation_id_place_insert(); Type: FUNCTION; Schema: dbmig; Owner: postgres
--

CREATE FUNCTION dbmig.observation_id_place_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  PERFORM op_id FROM "dbmig".observation_places WHERE op_id = NEW.op_id;
  IF FOUND THEN
	RAISE EXCEPTION '2- Invalid op_id (%)', NEW.op_id;
  ELSE
	RETURN NEW;
  END IF;
END
$$;


ALTER FUNCTION dbmig.observation_id_place_insert() OWNER TO diaspara_admin;

--
-- TOC entry 2638 (class 1255 OID 2557664)
-- Name: observation_id_place_update(); Type: FUNCTION; Schema: dbmig; Owner: postgres
--

CREATE FUNCTION dbmig.observation_id_place_update() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  IF NEW.op_id = OLD.op_id THEN
	RETURN NEW;
  ELSE
	RAISE EXCEPTION 'Do not update op_id (%)', OLD.op_id;
  END IF;
END
$$;


ALTER FUNCTION dbmig.observation_id_place_update() OWNER TO diaspara_admin;

--
-- TOC entry 2639 (class 1255 OID 2557665)
-- Name: observations_id_insert(); Type: FUNCTION; Schema: dbmig; Owner: postgres
--

CREATE FUNCTION dbmig.observations_id_insert() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  PERFORM ob_id FROM "dbmig".observations WHERE ob_id = NEW.ob_id;
  IF FOUND THEN
	RAISE EXCEPTION '3- Invalid ob_id (%)', NEW.ob_id;
  ELSE
	RETURN NEW;
  END IF;
END
$$;


ALTER FUNCTION dbmig.observations_id_insert() OWNER TO diaspara_admin;

--
-- TOC entry 2640 (class 1255 OID 2557666)
-- Name: observations_id_update(); Type: FUNCTION; Schema: dbmig; Owner: postgres
--

CREATE FUNCTION dbmig.observations_id_update() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  IF NEW.ob_id = OLD.ob_id THEN
	RETURN NEW;
  ELSE
	RAISE EXCEPTION 'Do not update ob_id (%)', OLD.ob_id;
  END IF;
END
$$;


ALTER FUNCTION dbmig.observations_id_update() OWNER TO diaspara_admin;

-- *************************************************
-- 3) Create tables and Views
-- !!!!!! BEWARE : When creating Views, you need dbell_nomenclature schema to be created !!!!!!
-- *************************************************

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 336 (class 1259 OID 2558333)
-- Name: batch; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.batch (
    ba_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    ba_no_species integer,
    ba_no_stage integer,
    ba_no_value_type integer,
    ba_no_biological_characteristic_type integer,
    ba_quantity real,
    ba_no_individual_status integer,
    ba_batch_level integer,
    ba_ob_id uuid NOT NULL,
    ba_ba_id uuid
);


ALTER TABLE dbmig.batch OWNER TO diaspara_admin;

--
-- TOC entry 337 (class 1259 OID 2558337)
-- Name: biological_characteristic; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.biological_characteristic (
    bc_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    bc_ba_id uuid NOT NULL,
    bc_no_characteristic_type integer NOT NULL,
    bc_no_value_type integer NOT NULL,
    bc_numvalue real
);


ALTER TABLE dbmig.biological_characteristic OWNER TO diaspara_admin;

--
-- TOC entry 338 (class 1259 OID 2558341)
-- Name: bypass; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.bypass (
    bypass_id uuid NOT NULL,
    bypass_hpp_id uuid,
    bypass_water_depth numeric,
    bypass_width numeric,
    bypass_is_flowing boolean
);


ALTER TABLE dbmig.bypass OWNER TO diaspara_admin;

--
-- TOC entry 339 (class 1259 OID 2558346)
-- Name: observations; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.observations (
    ob_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    ob_no_origin integer,
    ob_no_type integer,
    ob_no_period integer,
    ob_starting_date date,
    ob_ending_date date,
    ob_op_id uuid NOT NULL,
    ob_dp_id integer NOT NULL
);


ALTER TABLE dbmig.observations OWNER TO diaspara_admin;

--
-- TOC entry 340 (class 1259 OID 2558350)
-- Name: obstruction; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.obstruction (
    ot_no_obstruction_type integer,
    ot_obstruction_number integer,
    ot_no_mortality_type integer,
    ot_no_mortality real
)
INHERITS (dbmig.observations);


ALTER TABLE dbmig.obstruction OWNER TO diaspara_admin;

--
-- TOC entry 341 (class 1259 OID 2558354)
-- Name: chemical_obstruction; Type: TABLE; Schema: dbmig; Owner: postgres
--
/*
CREATE TABLE dbmig.chemical_obstruction (
    co_chemical_type character varying(30),
    co_pollution character varying(30),
    co_distribution_type character varying(30),
    co_distribution integer
)
INHERITS (dbmig.obstruction);


ALTER TABLE dbmig.chemical_obstruction OWNER TO diaspara_admin;
*/
--
-- TOC entry 342 (class 1259 OID 2558358)
-- Name: data_provider; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.data_provider (
    dp_id integer NOT NULL,
    dp_name character varying(60),
    dp_et_id integer
);


ALTER TABLE dbmig.data_provider OWNER TO diaspara_admin;

--
-- TOC entry 343 (class 1259 OID 2558361)
-- Name: data_provider_dp_id_seq; Type: SEQUENCE; Schema: dbmig; Owner: postgres
--

CREATE SEQUENCE dbmig.data_provider_dp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dbmig.data_provider_dp_id_seq OWNER TO diaspara_admin;

--
-- TOC entry 8243 (class 0 OID 0)
-- Dependencies: 343
-- Name: data_provider_dp_id_seq; Type: SEQUENCE OWNED BY; Schema: dbmig; Owner: postgres
--

ALTER SEQUENCE dbmig.data_provider_dp_id_seq OWNED BY dbmig.data_provider.dp_id;


--
-- TOC entry 344 (class 1259 OID 2558362)
-- Name: differentiation; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.differentiation (
    di_rate real,
    di_no_sex integer
)
INHERITS (dbmig.observations);


ALTER TABLE dbmig.differentiation OWNER TO diaspara_admin;

--
-- TOC entry 345 (class 1259 OID 2558366)
-- Name: ecological_status; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.ecological_status (
    es_no_statusclass integer
)
INHERITS (dbmig.observations);


ALTER TABLE dbmig.ecological_status OWNER TO diaspara_admin;

--
-- TOC entry 346 (class 1259 OID 2558370)
-- Name: electrofishing; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.electrofishing (
    ef_no_fishingmethod integer,
    ef_no_electrofishing_mean integer,
    ef_wetted_area real,
    ef_fished_length real,
    ef_fished_width real,
    ef_duration double precision,
    ef_nbpas integer
)
INHERITS (dbmig.observations);


ALTER TABLE dbmig.electrofishing OWNER TO diaspara_admin;

--
-- TOC entry 347 (class 1259 OID 2558374)
-- Name: environmental_characteristic; Type: TABLE; Schema: dbmig; Owner: postgres
--
/*
CREATE TABLE dbmig.environmental_characteristic (
    ec_id integer NOT NULL,
    ec_temperature real,
    ec_slope real,
    ec_distance_sea real,
    ec_wettered_area real,
    ec_no_ecologicalproduct integer,
    ec_noncalcareous_precent real,
    ec_op_id uuid
);


ALTER TABLE dbmig.environmental_characteristic OWNER TO diaspara_admin;
*/
--
-- TOC entry 348 (class 1259 OID 2558377)
-- Name: environmental_characteristic_ec_id_seq; Type: SEQUENCE; Schema: dbmig; Owner: postgres
--
/*
CREATE SEQUENCE dbmig.environmental_characteristic_ec_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dbmig.environmental_characteristic_ec_id_seq OWNER TO diaspara_admin;
*/
--
-- TOC entry 8244 (class 0 OID 0)
-- Dependencies: 348
-- Name: environmental_characteristic_ec_id_seq; Type: SEQUENCE OWNED BY; Schema: dbmig; Owner: postgres
--
/*
ALTER SEQUENCE dbmig.environmental_characteristic_ec_id_seq OWNED BY dbmig.environmental_characteristic.ec_id;
*/

--
-- TOC entry 349 (class 1259 OID 2558378)
-- Name: establishment; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.establishment (
    et_id integer NOT NULL,
    et_establishment_name character varying(100)
);


ALTER TABLE dbmig.establishment OWNER TO diaspara_admin;

--
-- TOC entry 350 (class 1259 OID 2558381)
-- Name: establishment_et_id_seq; Type: SEQUENCE; Schema: dbmig; Owner: postgres
--

CREATE SEQUENCE dbmig.establishment_et_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE dbmig.establishment_et_id_seq OWNER TO diaspara_admin;

--
-- TOC entry 8245 (class 0 OID 0)
-- Dependencies: 350
-- Name: establishment_et_id_seq; Type: SEQUENCE OWNED BY; Schema: dbmig; Owner: postgres
--

ALTER SEQUENCE dbmig.establishment_et_id_seq OWNED BY dbmig.establishment.et_id;


--
-- TOC entry 351 (class 1259 OID 2558382)
-- Name: predation; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.predation (
    pr_no_predation_type integer,
    pr_predator_number integer,
    pr_no_effort_unit integer,
    pr_effort_value real,
    pr_maxumin_length real,
    pr_minimum_length real
)
INHERITS (dbmig.observations);


ALTER TABLE dbmig.predation OWNER TO diaspara_admin;

--
-- TOC entry 352 (class 1259 OID 2558386)
-- Name: fishery; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.fishery (
    fi_no_fisher_type integer,
    fi_no_geartype integer
)
INHERITS (dbmig.predation);


ALTER TABLE dbmig.fishery OWNER TO diaspara_admin;

--
-- TOC entry 353 (class 1259 OID 2558390)
-- Name: gear_fishing; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.gear_fishing (
    gf_no_gear_type integer,
    gf_gear_number integer,
    gf_no_effort_type integer,
    gf_effort_value real,
    gf_no_name integer
)
INHERITS (dbmig.observations);


ALTER TABLE dbmig.gear_fishing OWNER TO diaspara_admin;

--
-- TOC entry 354 (class 1259 OID 2558394)
-- Name: growth; Type: TABLE; Schema: dbmig; Owner: postgres
--
/*
CREATE TABLE dbmig.growth (
    gr_rate real,
    gr_assymptotique_length real,
    gr_constante real
)
INHERITS (dbmig.observations);


ALTER TABLE dbmig.growth OWNER TO diaspara_admin;

--
-- TOC entry 355 (class 1259 OID 2558398)
-- Name: habitat_loss; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.habitat_loss (
    el_no_hahitat_losstype integer,
    el_no_unity_type integer,
    el_value real
)
INHERITS (dbmig.observations);


ALTER TABLE dbmig.habitat_loss OWNER TO diaspara_admin;
*/
--
-- TOC entry 356 (class 1259 OID 2558402)
-- Name: hpp; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.hpp (
    hpp_id uuid NOT NULL,
    hpp_ob_id uuid,
    hpp_name text,
    hpp_main_grid_or_production integer,
    hpp_presence_bypass boolean,
    hpp_total_flow_bypass numeric,
    hpp_orient_flow_no_id integer,
    hpp_presence_of_bar_rack boolean,
    hpp_bar_rack_space numeric,
    hpp_surface_bar_rack numeric,
    hpp_inclination_bar_rack numeric,
    hpp_presence_bypass_trashrack boolean,
    hpp_nb_trashrack_bypass integer,
    hpp_turb_max_flow numeric,
    hpp_reserved_flow numeric,
    hpp_flow_trashrack_bypass numeric,
    hpp_max_power numeric,
    hpp_nb_turbines integer,
    hpp_orientation_bar_rack numeric,
    hpp_id_original text,
    hpp_source text
);


ALTER TABLE dbmig.hpp OWNER TO diaspara_admin;

--
-- TOC entry 8246 (class 0 OID 0)
-- Dependencies: 356
-- Name: COLUMN hpp.hpp_inclination_bar_rack; Type: COMMENT; Schema: dbmig; Owner: postgres
--

COMMENT ON COLUMN dbmig.hpp.hpp_inclination_bar_rack IS 'Inclination of the bar rack, angle in degree between the bottom and the bar rack';


--
-- TOC entry 8247 (class 0 OID 0)
-- Dependencies: 356
-- Name: COLUMN hpp.hpp_orientation_bar_rack; Type: COMMENT; Schema: dbmig; Owner: postgres
--

COMMENT ON COLUMN dbmig.hpp.hpp_orientation_bar_rack IS 'Orientation of the bar rack, angle in degree between the bank and the bar rack';


--
-- TOC entry 357 (class 1259 OID 2558407)
-- Name: maturation; Type: TABLE; Schema: dbmig; Owner: postgres
--
/*
CREATE TABLE dbmig.maturation (
    ma_param1 real,
    ma_param2 real,
    ma_lenght integer,
    ma_no_sex integer
)
INHERITS (dbmig.observations);


ALTER TABLE dbmig.maturation OWNER TO diaspara_admin;

--
-- TOC entry 358 (class 1259 OID 2558411)
-- Name: migration; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.migration (
    mi_proportion real,
    mi_speed_unity character varying(30),
    mi_speed real,
    mi_arrival_op_id uuid
)
INHERITS (dbmig.observations);


ALTER TABLE dbmig.migration OWNER TO diaspara_admin;
*/
--
-- TOC entry 359 (class 1259 OID 2558415)
-- Name: migration_monitoring; Type: TABLE; Schema: dbmig; Owner: postgres
--

/*

CREATE TABLE dbmig.migration_monitoring (
    mm_no_monitoring_type integer,
    mm_no_monitoring_direction integer,
    mm_escapment_rate real,
    mm_no_name integer
)
INHERITS (dbmig.observations);


ALTER TABLE dbmig.migration_monitoring OWNER TO diaspara_admin;
*/
--
-- TOC entry 360 (class 1259 OID 2558419)
-- Name: mortality; Type: TABLE; Schema: dbmig; Owner: postgres
--


/*
CREATE TABLE dbmig.mortality (
    mo_no_mortality_type integer
)
INHERITS (dbmig.observations);


ALTER TABLE dbmig.mortality OWNER TO diaspara_admin;
*/
--
-- TOC entry 361 (class 1259 OID 2558423)
-- Name: observation_places; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.observation_places (
    op_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    op_gis_systemname character varying(20),
    op_gis_layername character varying(30),
    op_gislocation character varying(15),
    op_placename character varying(250),
    op_no_observationplacetype integer,
    op_op_id uuid,
    the_geom public.geometry,
    CONSTRAINT enforce_dims_the_geom CHECK ((public.st_ndims(the_geom) = 2)),
    CONSTRAINT enforce_geotype_the_geom CHECK (((public.geometrytype(the_geom) = 'POINT'::text) OR (the_geom IS NULL))),
    CONSTRAINT enforce_srid_the_geom CHECK ((public.st_srid(the_geom) = 3035))
);


ALTER TABLE dbmig.observation_places OWNER TO diaspara_admin;

--
-- TOC entry 366 (class 1259 OID 2558450)
-- Name: physical_obstruction; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.physical_obstruction (
    po_no_obstruction_passability integer,
    po_obstruction_height real,
    po_downs_pb boolean,
    po_downs_water_depth numeric,
    po_presence_eel_pass boolean,
    po_method_perm_ev text,
    po_date_presence_eel_pass date,
    mitigation_measure_no_id integer
)
INHERITS (dbmig.obstruction);


ALTER TABLE dbmig.physical_obstruction OWNER TO diaspara_admin;

--
-- TOC entry 8250 (class 0 OID 0)
-- Dependencies: 366
-- Name: COLUMN physical_obstruction.po_downs_pb; Type: COMMENT; Schema: dbmig; Owner: postgres
--

COMMENT ON COLUMN dbmig.physical_obstruction.po_downs_pb IS '¿Existe un problema para la migración aguas abajo? (Opinión de experto):
- Si el agua cae en una profundidad menor a un metro cerca de la presa, quiere decir que existe impacto (TRUE).
- Si el agua cae río abajo desde una presa con un salto de agua menor a cuatro metros, y que la profundidad del agua cerca de la presa es de un metro (sin rocas, ni otros obstáculos), entonces el impacto es nulo (FALSE); en caso contrario, existe impacto (TRUE).
- Si el salto de agua es mayor a cuatro metros, la profundidad del agua cerca de la presa debería ser ¼ parte del salto de agua. Esto debe ser medido en condiciones de fuerte caudal (que corresponde con la mayor parte de migración ríos abajo de las anguilas plateadas). Si la profundidad es menor de la indicada, entonces existe impacto (TRUE).';


--
-- TOC entry 8251 (class 0 OID 0)
-- Dependencies: 366
-- Name: COLUMN physical_obstruction.po_downs_water_depth; Type: COMMENT; Schema: dbmig; Owner: postgres
--

COMMENT ON COLUMN dbmig.physical_obstruction.po_downs_water_depth IS 'Water depth close to the dam';


--
-- TOC entry 8252 (class 0 OID 0)
-- Dependencies: 366
-- Name: COLUMN physical_obstruction.po_presence_eel_pass; Type: COMMENT; Schema: dbmig; Owner: postgres
--

COMMENT ON COLUMN dbmig.physical_obstruction.po_presence_eel_pass IS 'Presence of an eel pass';


--
-- TOC entry 8253 (class 0 OID 0)
-- Dependencies: 366
-- Name: COLUMN physical_obstruction.po_method_perm_ev; Type: COMMENT; Schema: dbmig; Owner: postgres
--

COMMENT ON COLUMN dbmig.physical_obstruction.po_method_perm_ev IS 'Permeability/ Impact evaluation method';


--
-- TOC entry 8254 (class 0 OID 0)
-- Dependencies: 366
-- Name: COLUMN physical_obstruction.po_date_presence_eel_pass; Type: COMMENT; Schema: dbmig; Owner: postgres
--

COMMENT ON COLUMN dbmig.physical_obstruction.po_date_presence_eel_pass IS 'Date of construction of an eel pass';


--
-- TOC entry 8255 (class 0 OID 0)
-- Dependencies: 366
-- Name: COLUMN physical_obstruction.mitigation_measure_no_id; Type: COMMENT; Schema: dbmig; Owner: postgres
--

COMMENT ON COLUMN dbmig.physical_obstruction.mitigation_measure_no_id IS 'Type of measure for downtream migration mitigation';

--
-- TOC entry 369 (class 1259 OID 2558465)
-- Name: stocking; Type: TABLE; Schema: dbmig; Owner: postgres
--

/*
CREATE TABLE dbmig.stocking (
    st_mortality_rate real,
    st_population_origin character varying(60)
)
INHERITS (dbmig.observations);


ALTER TABLE dbmig.stocking OWNER TO diaspara_admin;
*/
--
-- TOC entry 370 (class 1259 OID 2558469)
-- Name: turbine; Type: TABLE; Schema: dbmig; Owner: postgres
--

CREATE TABLE dbmig.turbine (
    turb_id uuid NOT NULL,
    turb_hpp_id uuid,
    turb_turbine_type_no_id integer,
    turb_in_service boolean,
    turb_max_power numeric,
    turb_min_working_flow numeric,
    turb_hpp_height numeric,
    turb_diameter numeric,
    turb_rotation_speed numeric,
    turb_nb_blades integer,
    turb_max_turbine_flow numeric,
    turb_description text
);


ALTER TABLE dbmig.turbine OWNER TO diaspara_admin;

--
-- TOC entry 371 (class 1259 OID 2558474)
-- Name: upstream; Type: TABLE; Schema: dbmig; Owner: postgres
--
/*
CREATE TABLE dbmig.upstream (
    up_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    up_op_id_parent uuid,
    up_op_id_child uuid
);


ALTER TABLE dbmig.upstream OWNER TO diaspara_admin;
*/

--
-- TOC entry 378 (class 1259 OID 2558500)
-- Name: wildlife; Type: TABLE; Schema: dbmig; Owner: postgres
--
/*
CREATE TABLE dbmig.wildlife (
    wi_no_species integer
)
INHERITS (dbmig.predation);


ALTER TABLE dbmig.wildlife OWNER TO diaspara_admin;
*/
--
-- TOC entry 379 (class 1259 OID 2558504)
-- Name: within; Type: TABLE; Schema: dbmig; Owner: postgres
--

/*

CREATE TABLE dbmig.within (
    wi_id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    wi_op_id_parent uuid,
    wi_op_id_child uuid
);


ALTER TABLE dbmig.within OWNER TO diaspara_admin;
*/
--
-- TOC entry 7674 (class 2604 OID 2562091)
-- Name: chemical_obstruction ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--

-- *************************************************
-- 4) Create autogenerated IDs with uuid_generate_v4 function
-- *************************************************
/*
ALTER TABLE ONLY dbmig.chemical_obstruction ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();
*/

--
-- TOC entry 7675 (class 2604 OID 2562092)
-- Name: data_provider dp_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.data_provider ALTER COLUMN dp_id SET DEFAULT nextval('dbmig.data_provider_dp_id_seq'::regclass);


--
-- TOC entry 7676 (class 2604 OID 2562093)
-- Name: differentiation ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--
/*
ALTER TABLE ONLY dbmig.differentiation ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();
*/

--
-- TOC entry 7677 (class 2604 OID 2562094)
-- Name: ecological_status ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--
/*
ALTER TABLE ONLY dbmig.ecological_status ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();
*/

--
-- TOC entry 7678 (class 2604 OID 2562095)
-- Name: electrofishing ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.electrofishing ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();


--
-- TOC entry 7679 (class 2604 OID 2562096)
-- Name: environmental_characteristic ec_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.environmental_characteristic ALTER COLUMN ec_id SET DEFAULT nextval('dbmig.environmental_characteristic_ec_id_seq'::regclass);


--
-- TOC entry 7680 (class 2604 OID 2562097)
-- Name: establishment et_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.establishment ALTER COLUMN et_id SET DEFAULT nextval('dbmig.establishment_et_id_seq'::regclass);


--
-- TOC entry 7682 (class 2604 OID 2562098)
-- Name: fishery ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.fishery ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();


--
-- TOC entry 7683 (class 2604 OID 2562099)
-- Name: gear_fishing ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.gear_fishing ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();


--
-- TOC entry 7684 (class 2604 OID 2562100)
-- Name: growth ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--
/*
ALTER TABLE ONLY dbmig.growth ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();
*/

--
-- TOC entry 7685 (class 2604 OID 2562101)
-- Name: habitat_loss ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--
/*
ALTER TABLE ONLY dbmig.habitat_loss ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();
*/

--
-- TOC entry 7686 (class 2604 OID 2562102)
-- Name: maturation ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--

/*
ALTER TABLE ONLY dbmig.maturation ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();
*/

--
-- TOC entry 7687 (class 2604 OID 2562103)
-- Name: migration ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--
/*
ALTER TABLE ONLY dbmig.migration ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();
*/

--
-- TOC entry 7688 (class 2604 OID 2562104)
-- Name: migration_monitoring ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--
/*
ALTER TABLE ONLY dbmig.migration_monitoring ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();
*/

--
-- TOC entry 7689 (class 2604 OID 2562105)
-- Name: mortality ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--
/*
ALTER TABLE ONLY dbmig.mortality ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();
*/
--
-- TOC entry 7673 (class 2604 OID 2562108)
-- Name: obstruction ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--


ALTER TABLE ONLY dbmig.obstruction ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();


--
-- TOC entry 7693 (class 2604 OID 2562109)
-- Name: physical_obstruction ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.physical_obstruction ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();


--
-- TOC entry 7681 (class 2604 OID 2562110)
-- Name: predation ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--
/*
ALTER TABLE ONLY dbmig.predation ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();
*/
--
-- TOC entry 7695 (class 2604 OID 2562112)
-- Name: stocking ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--
/*
ALTER TABLE ONLY dbmig.stocking ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();
*/

--
-- TOC entry 7697 (class 2604 OID 2562113)
-- Name: wildlife ob_id; Type: DEFAULT; Schema: dbmig; Owner: postgres
--
/*
ALTER TABLE ONLY dbmig.wildlife ALTER COLUMN ob_id SET DEFAULT public.uuid_generate_v4();
*/

-- *************************************************
-- 4) Add primary key constraints
-- *************************************************


--
-- TOC entry 7712 (class 2606 OID 6985857)
-- Name: batch batch_pkey; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.batch
    ADD CONSTRAINT batch_pkey PRIMARY KEY (ba_id);


--
-- TOC entry 7716 (class 2606 OID 6985859)
-- Name: biological_characteristic biological_characteristic_pkey; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.biological_characteristic
    ADD CONSTRAINT biological_characteristic_pkey PRIMARY KEY (bc_id);


--
-- TOC entry 7720 (class 2606 OID 6985861)
-- Name: bypass bypass_pkey; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.bypass
    ADD CONSTRAINT bypass_pkey PRIMARY KEY (bypass_id);


--
-- TOC entry 7726 (class 2606 OID 6985863)
-- Name: chemical_obstruction chemical_obstruction_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--
/*
ALTER TABLE ONLY dbmig.chemical_obstruction
    ADD CONSTRAINT chemical_obstruction_id PRIMARY KEY (ob_id);
*/

--
-- TOC entry 7728 (class 2606 OID 6985865)
-- Name: data_provider data_provider_pkey; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.data_provider
    ADD CONSTRAINT data_provider_pkey PRIMARY KEY (dp_id);


--
-- TOC entry 7730 (class 2606 OID 6985867)
-- Name: differentiation differentiation_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.differentiation
    ADD CONSTRAINT differentiation_id PRIMARY KEY (ob_id);


--
-- TOC entry 7732 (class 2606 OID 6985869)
-- Name: ecological_status ecological_status_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.ecological_status
    ADD CONSTRAINT ecological_status_id PRIMARY KEY (ob_id);


--
-- TOC entry 7736 (class 2606 OID 6985871)
-- Name: electrofishing electrofishing_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.electrofishing
    ADD CONSTRAINT electrofishing_id PRIMARY KEY (ob_id);


--
-- TOC entry 7738 (class 2606 OID 6985873)
-- Name: environmental_characteristic environmental_characteristic_pkey; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.environmental_characteristic
    ADD CONSTRAINT environmental_characteristic_pkey PRIMARY KEY (ec_id);


--
-- TOC entry 7740 (class 2606 OID 6985875)
-- Name: establishment establishment_pkey; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.establishment
    ADD CONSTRAINT establishment_pkey PRIMARY KEY (et_id);


--
-- TOC entry 7744 (class 2606 OID 6985877)
-- Name: fishery fishery_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.fishery
    ADD CONSTRAINT fishery_id PRIMARY KEY (ob_id);


--
-- TOC entry 7746 (class 2606 OID 6985879)
-- Name: gear_fishing gear_fishing_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.gear_fishing
    ADD CONSTRAINT gear_fishing_id PRIMARY KEY (ob_id);


--
-- TOC entry 7748 (class 2606 OID 6985881)
-- Name: growth growth_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

/*
ALTER TABLE ONLY dbmig.growth
    ADD CONSTRAINT growth_id PRIMARY KEY (ob_id);
*/

--
-- TOC entry 7750 (class 2606 OID 6985883)
-- Name: habitat_loss habitat_loss_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

/*

ALTER TABLE ONLY dbmig.habitat_loss
    ADD CONSTRAINT habitat_loss_id PRIMARY KEY (ob_id);
*/

--
-- TOC entry 7752 (class 2606 OID 6985885)
-- Name: hpp hpp_pkey; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.hpp
    ADD CONSTRAINT hpp_pkey PRIMARY KEY (hpp_id);


--
-- TOC entry 7754 (class 2606 OID 6985887)
-- Name: maturation maturation_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

/*
ALTER TABLE ONLY dbmig.maturation
    ADD CONSTRAINT maturation_id PRIMARY KEY (ob_id);
*/

--
-- TOC entry 7756 (class 2606 OID 6985889)
-- Name: migration migration_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

/*
ALTER TABLE ONLY dbmig.migration
    ADD CONSTRAINT migration_id PRIMARY KEY (ob_id);
*/

--
-- TOC entry 7758 (class 2606 OID 6985891)
-- Name: migration_monitoring migration_monitoring_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

/*
ALTER TABLE ONLY dbmig.migration_monitoring
    ADD CONSTRAINT migration_monitoring_id PRIMARY KEY (ob_id);
*/

--
-- TOC entry 7760 (class 2606 OID 6985893)
-- Name: mortality mortality_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--
/*
ALTER TABLE ONLY dbmig.mortality
    ADD CONSTRAINT mortality_id PRIMARY KEY (ob_id);
*/

--
-- TOC entry 7764 (class 2606 OID 6985895)
-- Name: observation_places observation_places_pkey; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.observation_places
    ADD CONSTRAINT observation_places_pkey PRIMARY KEY (op_id);


--
-- TOC entry 7722 (class 2606 OID 6985897)
-- Name: observations observations_pkey; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.observations
    ADD CONSTRAINT observations_pkey PRIMARY KEY (ob_id);


--
-- TOC entry 7724 (class 2606 OID 6985899)
-- Name: obstruction obstruction_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.obstruction
    ADD CONSTRAINT obstruction_id PRIMARY KEY (ob_id);


--
-- TOC entry 7769 (class 2606 OID 6985901)
-- Name: physical_obstruction physical_obstruction_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.physical_obstruction
    ADD CONSTRAINT physical_obstruction_id PRIMARY KEY (ob_id);

--
-- TOC entry 7742 (class 2606 OID 6985905)
-- Name: predation predation_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

/*
ALTER TABLE ONLY dbmig.predation
    ADD CONSTRAINT predation_id PRIMARY KEY (ob_id);
*/

--
-- TOC entry 7772 (class 2606 OID 6985907)
-- Name: stocking stocking_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

/*
ALTER TABLE ONLY dbmig.stocking
    ADD CONSTRAINT stocking_id PRIMARY KEY (ob_id);
*/

--
-- TOC entry 7774 (class 2606 OID 6985909)
-- Name: turbine turbine_pkey; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.turbine
    ADD CONSTRAINT turbine_pkey PRIMARY KEY (turb_id);


--
-- TOC entry 7776 (class 2606 OID 6985911)
-- Name: upstream upstream_pkey; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--
/*
ALTER TABLE ONLY dbmig.upstream
    ADD CONSTRAINT upstream_pkey PRIMARY KEY (up_id);
*/

--
-- TOC entry 7778 (class 2606 OID 6985913)
-- Name: wildlife wildlife_id; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

ALTER TABLE ONLY dbmig.wildlife
    ADD CONSTRAINT wildlife_id PRIMARY KEY (ob_id);


--
-- TOC entry 7780 (class 2606 OID 6985915)
-- Name: within within_pkey; Type: CONSTRAINT; Schema: dbmig; Owner: postgres
--

/*
ALTER TABLE ONLY dbmig.within
    ADD CONSTRAINT within_pkey PRIMARY KEY (wi_id);
*/
-- *************************************************
-- 5) Creating Indexes with B-Trees
-- *************************************************


--
-- TOC entry 7713 (class 1259 OID 6986804)
-- Name: dbmig_batch_ix_ba_id; Type: INDEX; Schema: dbmig; Owner: postgres
--

CREATE INDEX dbmig_batch_ix_ba_id ON dbmig.batch USING btree (ba_id);


--
-- TOC entry 7714 (class 1259 OID 6986805)
-- Name: dbmig_batch_ix_ba_ob_id; Type: INDEX; Schema: dbmig; Owner: postgres
--

CREATE INDEX dbmig_batch_ix_ba_ob_id ON dbmig.batch USING btree (ba_ob_id);


--
-- TOC entry 7717 (class 1259 OID 6986806)
-- Name: dbmig_biological_characteristic_ix_bc_ba_id; Type: INDEX; Schema: dbmig; Owner: postgres
--

CREATE INDEX dbmig_biological_characteristic_ix_bc_ba_id ON dbmig.biological_characteristic USING btree (bc_ba_id);


--
-- TOC entry 7718 (class 1259 OID 6986807)
-- Name: dbmig_biological_characteristic_ix_bc_id; Type: INDEX; Schema: dbmig; Owner: postgres
--

CREATE INDEX dbmig_biological_characteristic_ix_bc_id ON dbmig.biological_characteristic USING btree (bc_id);


--
-- TOC entry 7733 (class 1259 OID 6986808)
-- Name: dbmig_electrofishing_ix_ob_id; Type: INDEX; Schema: dbmig; Owner: postgres
--

CREATE INDEX dbmig_electrofishing_ix_ob_id ON dbmig.electrofishing USING btree (ob_id);


--
-- TOC entry 7734 (class 1259 OID 6986809)
-- Name: dbmig_electrofishing_ix_ob_op_id; Type: INDEX; Schema: dbmig; Owner: postgres
--

CREATE INDEX dbmig_electrofishing_ix_ob_op_id ON dbmig.electrofishing USING btree (ob_op_id);


--
-- TOC entry 7761 (class 1259 OID 6986810)
-- Name: dbmig_observation_place_ix_op_id; Type: INDEX; Schema: dbmig; Owner: postgres
--

CREATE INDEX dbmig_observation_place_ix_op_id ON dbmig.observation_places USING btree (op_id);


--
-- TOC entry 7762 (class 1259 OID 6986811)
-- Name: indexgeobs; Type: INDEX; Schema: dbmig; Owner: postgres
--

CREATE INDEX indexgeobs ON dbmig.observation_places USING gist (the_geom);


-- *************************************************
-- 6) Linking insert/update with previsously created trigger functions
-- *************************************************


--
-- TOC entry 7899 (class 2620 OID 6987072)
-- Name: batch tr_batch_ob_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_batch_ob_id_insert BEFORE INSERT OR UPDATE ON dbmig.batch FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_batch_insert();


--
-- TOC entry 7908 (class 2620 OID 6987073)
-- Name: chemical_obstruction tr_chemical_obstruction_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_chemical_obstruction_insert BEFORE INSERT ON dbmig.chemical_obstruction FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();
*/

--
-- TOC entry 7909 (class 2620 OID 6987074)
-- Name: chemical_obstruction tr_chemical_obstruction_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_chemical_obstruction_update BEFORE UPDATE ON dbmig.chemical_obstruction FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();
*/

--
-- TOC entry 7912 (class 2620 OID 6987075)
-- Name: differentiation tr_differentiation_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_differentiation_insert BEFORE INSERT ON dbmig.differentiation FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();
*/

--
-- TOC entry 7913 (class 2620 OID 6987076)
-- Name: differentiation tr_differentiation_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_differentiation_update BEFORE UPDATE ON dbmig.differentiation FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();
*/

--
-- TOC entry 7916 (class 2620 OID 6987077)
-- Name: ecological_status tr_ecological_status_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_ecological_status_insert BEFORE INSERT ON dbmig.ecological_status FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();


--
-- TOC entry 7917 (class 2620 OID 6987078)
-- Name: ecological_status tr_ecological_status_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_ecological_status_update BEFORE UPDATE ON dbmig.ecological_status FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();


--
-- TOC entry 7920 (class 2620 OID 6987079)
-- Name: electrofishing tr_electrofishing_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_electrofishing_insert BEFORE INSERT ON dbmig.electrofishing FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();


--
-- TOC entry 7921 (class 2620 OID 6987080)
-- Name: electrofishing tr_electrofishing_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_electrofishing_update BEFORE UPDATE ON dbmig.electrofishing FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();


--
-- TOC entry 7924 (class 2620 OID 6987081)
-- Name: environmental_characteristic tr_environmental_characteristic_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_environmental_characteristic_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.environmental_characteristic FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_environmental_characteristic_insert();


--
-- TOC entry 7929 (class 2620 OID 6987082)
-- Name: fishery tr_fishery_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_fishery_insert BEFORE INSERT ON dbmig.fishery FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();


--
-- TOC entry 7930 (class 2620 OID 6987083)
-- Name: fishery tr_fishery_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_fishery_update BEFORE UPDATE ON dbmig.fishery FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();


--
-- TOC entry 7933 (class 2620 OID 6987084)
-- Name: gear_fishing tr_gearfishing_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_gearfishing_insert BEFORE INSERT ON dbmig.gear_fishing FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();


--
-- TOC entry 7934 (class 2620 OID 6987085)
-- Name: gear_fishing tr_gearfishing_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_gearfishing_update BEFORE UPDATE ON dbmig.gear_fishing FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();


--
-- TOC entry 7937 (class 2620 OID 6987086)
-- Name: growth tr_growth_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_growth_insert BEFORE INSERT ON dbmig.growth FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();
*/

--
-- TOC entry 7938 (class 2620 OID 6987087)
-- Name: growth tr_growth_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_growth_update BEFORE UPDATE ON dbmig.growth FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();
*/

--
-- TOC entry 7941 (class 2620 OID 6987088)
-- Name: habitat_loss tr_habitat_loss_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_habitat_loss_insert BEFORE INSERT ON dbmig.habitat_loss FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();
*/

--
-- TOC entry 7942 (class 2620 OID 6987089)
-- Name: habitat_loss tr_habitat_loss_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_habitat_loss_update BEFORE UPDATE ON dbmig.habitat_loss FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();
*/

--
-- TOC entry 7945 (class 2620 OID 6987090)
-- Name: maturation tr_maturation_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_maturation_insert BEFORE INSERT ON dbmig.maturation FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();
*/

--
-- TOC entry 7946 (class 2620 OID 6987091)
-- Name: maturation tr_maturation_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_maturation_update BEFORE UPDATE ON dbmig.maturation FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();
*/

--
-- TOC entry 7949 (class 2620 OID 6987092)
-- Name: migration tr_migration_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

/*
CREATE TRIGGER tr_migration_insert BEFORE INSERT ON dbmig.migration FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();
*/

--
-- TOC entry 7953 (class 2620 OID 6987093)
-- Name: migration_monitoring tr_migration_monitoring_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_migration_monitoring_insert BEFORE INSERT ON dbmig.migration_monitoring FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();
*/

--
-- TOC entry 7954 (class 2620 OID 6987094)
-- Name: migration_monitoring tr_migration_monitoring_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_migration_monitoring_update BEFORE UPDATE ON dbmig.migration_monitoring FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();
*/

--
-- TOC entry 7950 (class 2620 OID 6987095)
-- Name: migration tr_migration_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_migration_update BEFORE UPDATE ON dbmig.migration FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();
*/

--
-- TOC entry 7957 (class 2620 OID 6987096)
-- Name: mortality tr_mortality_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_mortality_insert BEFORE INSERT ON dbmig.mortality FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();
*/

--
-- TOC entry 7958 (class 2620 OID 6987097)
-- Name: mortality tr_mortality_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_mortality_update BEFORE UPDATE ON dbmig.mortality FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();
*/

--
-- TOC entry 7961 (class 2620 OID 6987098)
-- Name: observation_places tr_observation_places_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observation_places_delete BEFORE DELETE ON dbmig.observation_places FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observation_places_verify();


--
-- TOC entry 7962 (class 2620 OID 6987099)
-- Name: observation_places tr_observation_places_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observation_places_insert BEFORE INSERT ON dbmig.observation_places FOR EACH ROW EXECUTE FUNCTION dbmig.observation_id_place_insert();


--
-- TOC entry 7963 (class 2620 OID 6987100)
-- Name: observation_places tr_observation_places_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observation_places_update BEFORE UPDATE ON dbmig.observation_places FOR EACH ROW EXECUTE FUNCTION dbmig.observation_id_place_update();


--
-- TOC entry 7910 (class 2620 OID 6987101)
-- Name: chemical_obstruction tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.chemical_obstruction FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();
*/

--
-- TOC entry 7914 (class 2620 OID 6987102)
-- Name: differentiation tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.differentiation FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();
*/

--
-- TOC entry 7918 (class 2620 OID 6987103)
-- Name: ecological_status tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.ecological_status FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();


--
-- TOC entry 7922 (class 2620 OID 6987104)
-- Name: electrofishing tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.electrofishing FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();


--
-- TOC entry 7931 (class 2620 OID 6987105)
-- Name: fishery tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.fishery FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();


--
-- TOC entry 7935 (class 2620 OID 6987106)
-- Name: gear_fishing tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.gear_fishing FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();


--
-- TOC entry 7939 (class 2620 OID 6987107)
-- Name: growth tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.growth FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();
*/

--
-- TOC entry 7943 (class 2620 OID 6987108)
-- Name: habitat_loss tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.habitat_loss FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();
*/

--
-- TOC entry 7947 (class 2620 OID 6987109)
-- Name: maturation tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.maturation FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();
*/

--
-- TOC entry 7951 (class 2620 OID 6987110)
-- Name: migration tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.migration FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();
*/

--
-- TOC entry 7955 (class 2620 OID 6987111)
-- Name: migration_monitoring tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.migration_monitoring FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();
*/

--
-- TOC entry 7959 (class 2620 OID 6987112)
-- Name: mortality tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.mortality FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();
*/

--
-- TOC entry 7900 (class 2620 OID 6987113)
-- Name: observations tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.observations FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();


--
-- TOC entry 7904 (class 2620 OID 6987114)
-- Name: obstruction tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.obstruction FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();


--
-- TOC entry 7964 (class 2620 OID 6987115)
-- Name: physical_obstruction tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.physical_obstruction FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();


--
-- TOC entry 7925 (class 2620 OID 6987116)
-- Name: predation tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.predation FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();
*/

--
-- TOC entry 7968 (class 2620 OID 6987117)
-- Name: stocking tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.stocking FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();
*/

--
-- TOC entry 7972 (class 2620 OID 6987118)
-- Name: wildlife tr_observations_delete; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_delete BEFORE DELETE ON dbmig.wildlife FOR EACH ROW EXECUTE FUNCTION dbmig.integrity_observations_verify();
*/

--
-- TOC entry 7901 (class 2620 OID 6987119)
-- Name: observations tr_observations_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_insert BEFORE INSERT ON dbmig.observations FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();


--
-- TOC entry 7911 (class 2620 OID 6987120)
-- Name: chemical_obstruction tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.chemical_obstruction FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();
*/

--
-- TOC entry 7915 (class 2620 OID 6987121)
-- Name: differentiation tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.differentiation FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();
*/

--
-- TOC entry 7919 (class 2620 OID 6987122)
-- Name: ecological_status tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.ecological_status FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();


--
-- TOC entry 7923 (class 2620 OID 6987123)
-- Name: electrofishing tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.electrofishing FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();


--
-- TOC entry 7932 (class 2620 OID 6987124)
-- Name: fishery tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.fishery FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();


--
-- TOC entry 7936 (class 2620 OID 6987125)
-- Name: gear_fishing tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.gear_fishing FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();


--
-- TOC entry 7940 (class 2620 OID 6987126)
-- Name: growth tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.growth FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();
*/

--
-- TOC entry 7944 (class 2620 OID 6987127)
-- Name: habitat_loss tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.habitat_loss FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();
*/

--
-- TOC entry 7948 (class 2620 OID 6987128)
-- Name: maturation tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.maturation FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();
*/

--
-- TOC entry 7952 (class 2620 OID 6987129)
-- Name: migration tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.migration FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();
*/

--
-- TOC entry 7956 (class 2620 OID 6987130)
-- Name: migration_monitoring tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.migration_monitoring FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();
*/

--
-- TOC entry 7960 (class 2620 OID 6987131)
-- Name: mortality tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.mortality FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();
*/

--
-- TOC entry 7902 (class 2620 OID 6987132)
-- Name: observations tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.observations FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();


--
-- TOC entry 7905 (class 2620 OID 6987133)
-- Name: obstruction tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.obstruction FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();


--
-- TOC entry 7965 (class 2620 OID 6987134)
-- Name: physical_obstruction tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.physical_obstruction FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();


--
-- TOC entry 7926 (class 2620 OID 6987135)
-- Name: predation tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.predation FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();
*/

--
-- TOC entry 7969 (class 2620 OID 6987136)
-- Name: stocking tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.stocking FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();
*/

--
-- TOC entry 7973 (class 2620 OID 6987137)
-- Name: wildlife tr_observations_op_id_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_observations_op_id_insert BEFORE INSERT OR UPDATE ON dbmig.wildlife FOR EACH ROW EXECUTE FUNCTION dbmig.fk_id_observations_insert();
*/

--
-- TOC entry 7903 (class 2620 OID 6987138)
-- Name: observations tr_observations_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_observations_update BEFORE UPDATE ON dbmig.observations FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();


--
-- TOC entry 7906 (class 2620 OID 6987139)
-- Name: obstruction tr_obstruction_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_obstruction_insert BEFORE INSERT ON dbmig.obstruction FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();


--
-- TOC entry 7907 (class 2620 OID 6987140)
-- Name: obstruction tr_obstruction_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_obstruction_update BEFORE UPDATE ON dbmig.obstruction FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();


--
-- TOC entry 7966 (class 2620 OID 6987141)
-- Name: physical_obstruction tr_physical_obstruction_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_physical_obstruction_insert BEFORE INSERT ON dbmig.physical_obstruction FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();


--
-- TOC entry 7967 (class 2620 OID 6987142)
-- Name: physical_obstruction tr_physical_obstruction_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_physical_obstruction_update BEFORE UPDATE ON dbmig.physical_obstruction FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();


--
-- TOC entry 7927 (class 2620 OID 6987143)
-- Name: predation tr_predation_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_predation_insert BEFORE INSERT ON dbmig.predation FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();


--
-- TOC entry 7928 (class 2620 OID 6987144)
-- Name: predation tr_predation_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--

CREATE TRIGGER tr_predation_update BEFORE UPDATE ON dbmig.predation FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();


--
-- TOC entry 7970 (class 2620 OID 6987145)
-- Name: stocking tr_stocking_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_stocking_insert BEFORE INSERT ON dbmig.stocking FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();
*/

--
-- TOC entry 7971 (class 2620 OID 6987146)
-- Name: stocking tr_stocking_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_stocking_update BEFORE UPDATE ON dbmig.stocking FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();
*/

--
-- TOC entry 7974 (class 2620 OID 6987147)
-- Name: wildlife tr_wildlife_insert; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_wildlife_insert BEFORE INSERT ON dbmig.wildlife FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_insert();
*/

--
-- TOC entry 7975 (class 2620 OID 6987148)
-- Name: wildlife tr_wildlife_update; Type: TRIGGER; Schema: dbmig; Owner: postgres
--
/*
CREATE TRIGGER tr_wildlife_update BEFORE UPDATE ON dbmig.wildlife FOR EACH ROW EXECUTE FUNCTION dbmig.observations_id_update();
*/


-- *************************************************
-- 8) grant functions and tables to diaspara_read
-- *************************************************

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA dbmig TO diaspara_read;
GRANT select ON ALL tables IN SCHEMA dbmig TO diaspara_read;
